version: '3.8'

services:
  tournament-app:
    build: .
    container_name: tournament_manager
    ports:
      - "5000:5000"
    volumes:
      # --- HIER IST DER WICHTIGE TEIL ---
      # Links: Dein PC | Rechts: Der Container
      
      # 1. Die Datenbank-Datei sichern:
      - ./tournament.db:/app/tournament.db
      
      # 2. Die Map-Bilder sichern:
      - ./static/map_images:/app/static/map_images
      # ----------------------------------
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production